name: Bug Report
description: Submit a bug to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a report! Please provide as much detail as possible to help us quickly identify the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please clearly describe the bug you encountered
      placeholder: For example, The page crashes after clicking the button, with console error XXX
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this issue?
      placeholder: |
        1. Open page XXX
        2. Click the XXX button
        3. Observe the XXX phenomenon
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Operating system, browser version, etc. (optional but recommended)
      placeholder: |
        OS: Windows 11
        Browser: Chrome 118.0.5993.88

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might help resolve the issue (e.g., screenshots, logs)